// <auto-generated />
using AddToCartWithSess.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AddToCartWithSess.Migrations
{
    [DbContext(typeof(VegetableContext))]
    [Migration("20191101125635_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AddToCartWithSess.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cart")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("Image")
                        .HasMaxLength(500);

                    b.Property<decimal>("Price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, Cart = "<i class='ion-ios-cart'></i>", Image = "product-1.jpg", Price = 80m, Title = "BELL PEPPER" },
                        new { Id = 2, Cart = "<i class='ion-ios-cart'></i>", Image = "product-2.jpg", Price = 120m, Title = "STRAWBERRY" },
                        new { Id = 3, Cart = "<i class='ion-ios-cart'></i>", Image = "product-3.jpg", Price = 180m, Title = "GREEN BEANS" },
                        new { Id = 4, Cart = "<i class='ion-ios-cart'></i>", Image = "product-4.jpg", Price = 220m, Title = "PURPLE CABBAGE" },
                        new { Id = 5, Cart = "<i class='ion-ios-cart'></i>", Image = "product-5.jpg", Price = 110m, Title = "TOMATO" },
                        new { Id = 6, Cart = "<i class='ion-ios-cart'></i>", Image = "product-6.jpg", Price = 90m, Title = "BROCOLLI" },
                        new { Id = 7, Cart = "<i class='ion-ios-cart'></i>", Image = "product-7.jpg", Price = 100m, Title = "CARROTS" },
                        new { Id = 8, Cart = "<i class='ion-ios-cart'></i>", Image = "product-8.jpg", Price = 130m, Title = "FRUIT JUICE" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
